nilaibesar:  nilaibesar.o
  g++  nilaibesar.o  -o  nilaibesar

nilaibesar.o:  nilaibesar.cpp
g++  -c  nilaibesar.cpp  -o  nilaibesar.o

run:  nilaibesar
  ./nilaibesar

clean:
  rm  -f  nilaibesar.o  nilaibesar
