quadraticequations: quadraticequations.o
  g++  quadraticequations  .o  -o  quadraticequations

quadraticequations.o: quadraticequations.cpp
  g++  -c  quadraticequations.cpp  -o  quadraticequations.o

run:  quadraticequations
  ./quadraticequations

clean:
  rm  -f  quadraticequations.o  quadraticequations
