nilaideterminan:  nilaideterminan.o
  g++ nilaideterminan .o  -o  PaySlip

PaySlip.o:  nilaideterminan.cpp
  g++  -c  nilaideterminan.cpp  -o   nilaideterminan.o

run:  nilaideterminan
  ./nilaideterminan

clean:
  rm  -f  nilaideterminan.o  nilaideterminan
